run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - bodyclose
    - errcheck
    - govet
    - staticcheck
    - gosec

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  errcheck:
    check-type-assertions: true
  gosec:
    excludes: []
  staticcheck:
    checks: ["all"]

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters: [gosec]
