package manifestderive

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/gautamtalksdev/lading/internal/manifest"
	"gopkg.in/yaml.v3"
)

// ComponentCoverage is per-component CVE classification.
type ComponentCoverage struct {
	CVEs       []CVECoverage
	Name       string
	Ecosystem  string
	Definitive int // ≥1 definitive symbol
	Probable   int // symbols present but none definitive
	None       int // entry with zero symbols (should be rare)
}

// CVECoverage is one CVE's coverage class.
type CVECoverage struct {
	CVE   string
	Class string // definitive | probable | none
}

// CoverageReport is the full Manifest coverage snapshot.
type CoverageReport struct {
	Generated string
	Version   string
	Components []ComponentCoverage
}

// ComputeCoverage inspects promoted components (and optional candidates).
func ComputeCoverage(manifestDir string) (*CoverageReport, error) {
	m, err := manifest.Load(manifestDir)
	if err != nil {
		return nil, err
	}
	rep := &CoverageReport{
		Generated: time.Now().UTC().Format(time.RFC3339),
		Version:   m.Version(),
	}

	comps := m.Components()
	sort.Slice(comps, func(i, j int) bool {
		if comps[i].Ecosystem != comps[j].Ecosystem {
			return comps[i].Ecosystem < comps[j].Ecosystem
		}
		return comps[i].Name < comps[j].Name
	})

	// Re-read entries per component from byCVE is awkward; walk files again.
	compRoot := filepath.Join(manifestDir, "components")
	err = filepath.WalkDir(compRoot, func(path string, d os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if d.IsDir() {
			return nil
		}
		ext := strings.ToLower(filepath.Ext(path))
		if ext != ".yaml" && ext != ".yml" {
			return nil
		}
		cc, cerr := coverageFromFile(path)
		if cerr != nil {
			return cerr
		}
		rep.Components = append(rep.Components, cc)
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Slice(rep.Components, func(i, j int) bool {
		if rep.Components[i].Ecosystem != rep.Components[j].Ecosystem {
			return rep.Components[i].Ecosystem < rep.Components[j].Ecosystem
		}
		return rep.Components[i].Name < rep.Components[j].Name
	})

	// Candidates: all probable until promoted.
	candRoot := filepath.Join(manifestDir, "candidates")
	if st, err := os.Stat(candRoot); err == nil && st.IsDir() {
		_ = filepath.WalkDir(candRoot, func(path string, d os.DirEntry, walkErr error) error {
			if walkErr != nil || d.IsDir() {
				return walkErr
			}
			ext := strings.ToLower(filepath.Ext(path))
			if ext != ".yaml" && ext != ".yml" {
				return nil
			}
			cc, err := coverageFromCandidate(path)
			if err != nil {
				return nil // skip malformed candidates
			}
			cc.Name = cc.Name + " (candidate)"
			rep.Components = append(rep.Components, cc)
			return nil
		})
	}
	return rep, nil
}

func coverageFromFile(path string) (ComponentCoverage, error) {
	data, err := os.ReadFile(path) // #nosec G304
	if err != nil {
		return ComponentCoverage{}, err
	}
	var doc struct {
		Component struct {
			Name      string `yaml:"name"`
			Ecosystem string `yaml:"ecosystem"`
		} `yaml:"component"`
		Entries []struct {
			CVE               string `yaml:"cve"`
			VulnerableSymbols []struct {
				Confidence string `yaml:"confidence"`
			} `yaml:"vulnerable_symbols"`
		} `yaml:"entries"`
	}
	if err := yaml.Unmarshal(data, &doc); err != nil {
		return ComponentCoverage{}, err
	}
	cc := ComponentCoverage{Name: doc.Component.Name, Ecosystem: doc.Component.Ecosystem}
	for _, e := range doc.Entries {
		class := classifySymbols(e.VulnerableSymbols)
		cc.CVEs = append(cc.CVEs, CVECoverage{CVE: e.CVE, Class: class})
		switch class {
		case "definitive":
			cc.Definitive++
		case "probable":
			cc.Probable++
		default:
			cc.None++
		}
	}
	return cc, nil
}

func coverageFromCandidate(path string) (ComponentCoverage, error) {
	return coverageFromFile(path)
}

func classifySymbols(syms []struct {
	Confidence string `yaml:"confidence"`
}) string {
	if len(syms) == 0 {
		return "none"
	}
	for _, s := range syms {
		if s.Confidence == string(manifest.ConfidenceDefinitive) {
			return "definitive"
		}
	}
	return "probable"
}

// WriteCoverageMarkdown writes manifest/COVERAGE.md (generated, not hand-edited).
func WriteCoverageMarkdown(manifestDir string, rep *CoverageReport) error {
	var b strings.Builder
	b.WriteString("# Manifest Coverage\n\n")
	b.WriteString("<!-- GENERATED by `lading manifest coverage` — do not edit by hand -->\n\n")
	b.WriteString(fmt.Sprintf("Generated: %s\n\n", rep.Generated))
	b.WriteString(fmt.Sprintf("Manifest version: `%s`\n\n", rep.Version))
	b.WriteString("| Component | Ecosystem | Definitive CVEs | Probable-only CVEs | None |\n")
	b.WriteString("|-----------|-----------|-----------------|--------------------|------|\n")
	for _, c := range rep.Components {
		b.WriteString(fmt.Sprintf("| %s | %s | %d | %d | %d |\n",
			c.Name, c.Ecosystem, c.Definitive, c.Probable, c.None))
	}
	b.WriteString("\n## Per-CVE detail\n\n")
	for _, c := range rep.Components {
		b.WriteString(fmt.Sprintf("### %s (%s)\n\n", c.Name, c.Ecosystem))
		if len(c.CVEs) == 0 {
			b.WriteString("_No entries._\n\n")
			continue
		}
		for _, e := range c.CVEs {
			b.WriteString(fmt.Sprintf("- `%s`: **%s**\n", e.CVE, e.Class))
		}
		b.WriteString("\n")
	}
	b.WriteString("## Rules\n\n")
	b.WriteString("- **definitive** — ≥1 symbol with `confidence: definitive` (manual promote only).\n")
	b.WriteString("- **probable** — symbols present, none definitive (derive output / unreviewed).\n")
	b.WriteString("- **none** — entry with zero vulnerable symbols.\n")
	b.WriteString("- Automation (`lading manifest derive`) never writes definitive.\n")

	path := filepath.Join(manifestDir, "COVERAGE.md")
	return os.WriteFile(path, []byte(b.String()), 0o644) // #nosec G306 -- COVERAGE.md is documentation
}
